services:
  scanner:
    build:
      context: .
      network: host
    network_mode: host
    env_file: .env
    restart: always
    volumes:
      - ./reports:/app/reports
    command: ["python", "main.py"]

  ui:
    build:
      context: .
      network: host
    network_mode: host
    env_file: .env
    restart:  always
    volumes:
      - ./reports:/app/reports
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "9000"]
